# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#https://github.com/marketplace/actions/run-databricks-notebook
# TO DO: Write A New Package For Setting Environment Variables From A Parameters File.

name: Synapse_Deploy

on: push
#on: [workflow_dispatch] 

permissions:
      id-token:               write
      contents:               read

jobs:       
    DBX_CICD_Deployment:
      name:                     Synapse_Deploy
      runs-on:                  ubuntu-latest
      strategy:
        matrix:
          # Aligns To Environment Parameter File Names..
          environments:          [Development]   
      steps:

        - uses:                  actions/checkout@v3  

# 2.  Login To Main Service Principal.
        - name:                 Azure Login - ${{ matrix.environments }}
          uses:                 azure/login@v1
          with:
            creds:              ${{secrets.AZURE_CREDENTIALS}} 


# 3.  Create Env Variables From Parameters Files
        - name:                 .github/workflows/Pipeline_Param --> Env Variables
          uses:                 antifree/json-to-variables@v1.0.1
          with:
            filename:           '.github/workflows/Pipeline_Param/${{ matrix.environments }}.json'
            prefix:             pipeline
        

        - name:                 Infrastructure/DBX_CICD_Deployment/BICEP_Params --> Env Variables
          uses:                 antifree/json-to-variables@v1.0.1
          with:
            filename:           'Infrastructure/DBX_CICD_Deployment/Bicep_Params/${{ matrix.environments }}/Bicep.parameters.json'
            prefix:             bicep


        - name:                   Git Configure Dev Workspace 
          run:                    bash ./.github/workflows/Utilities/Utils-Synapse-Dev-Git-Config.sh
          env:
            environment:          ${{ matrix.environments }}
  










# 1.  Checkout Repo Containing Artifacts
        - uses:                  actions/checkout@v3  
          with:
            repository: 'ciaran28/SynapseArtifacts'
            ref: 'main'

        # Federated connections (below)..
        # https://goodworkaround.com/2021/12/21/another-deep-dive-into-azure-ad-workload-identity-federation-using-github-actions/


        - uses: Azure/Synapse-workspace-deployment@V1.7.0
          with:
            TargetWorkspaceName: 'synapsewsdeploychd'
            environment: 'Azure Public'
            ArtifactsFolder: 'synapseresources'
            resourceGroup: 'synapse-dev-rg'
            clientId: ${{ secrets.CLIENTID }}
            clientSecret: ${{ secrets.CLIENTSECRET }}
            subscriptionId: ${{ secrets.SUBID }}
            tenantId: ${{ secrets.TENANTID }}
            operation: 'validateDeploy'
